version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-remotewrite-loaded.yml:/etc/prometheus/prometheus-remotewrite-loaded.yml
    ports:
      - "9090:9090"
    networks:
      - code_default

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.35.1
    command:
      - sidecar
      - --tsdb.path=/var/prometheus
      - --prometheus.url=http://prometheus:9090
      - --grpc-address=0.0.0.0:10941
      - --http-address=0.0.0.0:10942
      - --log.level=debug
    volumes:
      - ./prometheus-data:/var/prometheus
    depends_on:
      - prometheus
    ports:
      - "10941:10941"
      - "10942:10942"
    networks:
      - code_default

  thanos-query:
    image: quay.io/thanos/thanos:v0.35.1
    command:
      - query
      - --http-address=0.0.0.0:9091
      - --store=thanos-sidecar:10941
      - --store=thanos-receive:10941
      - --log.level=debug
    depends_on:
      - thanos-sidecar
      - thanos-receive
    ports:
      - "9091:9091"
    networks:
      - code_default

  thanos-receive:
    image: quay.io/thanos/thanos:v0.35.1
    command:
      - receive
      - --http-address=0.0.0.0:10902
      - --grpc-address=0.0.0.0:10941
      - --remote-write.address=0.0.0.0:19291
      - --log.level=debug
      - --label=receive_replica=myreplicalabel
    ports:
      - "10941:10941"
      - "10902:10902"
      - "19291:19291"
    networks:
      - code_default

  busybox:
    image: busybox
    command: sh -c "while true; do echo 'Generating load'; sleep 1; done"
    networks:
      - code_default

networks:
  code_default:
    driver: bridge
