global:
  global:
    scrape_interval: 15s
    external_labels:
      cluster: 'your-cluster-name'
      region: 'your-region'

  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
