apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.35.1  # Ensure this is the correct image and tag
        args:
        - query
        - --http-address=0.0.0.0:9091
        - --store=thanos-sidecar:10901
        ports:
        - containerPort: 9091
